CREATE TABLE aircraft(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    model VARCHAR(25) NOT NULL,
    capacity SMALLINT NOT NULL
);

CREATE TABLE flights(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    aircraft_id BIGINT NOT NULL,
    departure TIMESTAMPTZ NOT NULL,
    arrival TIMESTAMPTZ NOT NULL,
    from VARCHAR(50) NOT NULL,
    to VARCHAR(50) NOT NULL,
);

CREATE TABLE bookings(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL,
    price SMALLINT NOT NULL
);
